name: RustCore
version: ${project.version}
main: dev.lightdream.rustcore.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
softdepend:
  - LightDreamAPI
commands:
  rc:
    description: NA
  ld-api:
    description: NA